name: cicd
on:
  push:
    branches:
      - main
jobs:
  dump-github-context:
    runs-on: ubuntu-latest

    name: Print event
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
