name: cicd
on:
  push:
    branches:
      - main
jobs:
  ExampleJob:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

